"""Small multi-label classifier (generated by model-scaffold).

A compact CNN for a forward-pass smoke test; for production swap in a pretrained `timm`
backbone (ResNet/DenseNet/EfficientNet/ViT) with a multi-label head.
"""
import torch
import torch.nn as nn


class SmallClassifier(nn.Module):
    def __init__(self, in_channels=1, num_classes=2, base=16):
        super().__init__()
        self.features = nn.Sequential(
            nn.Conv2d(in_channels, base, 3, padding=1), nn.BatchNorm2d(base), nn.ReLU(inplace=True),
            nn.MaxPool2d(2),
            nn.Conv2d(base, base * 2, 3, padding=1), nn.BatchNorm2d(base * 2), nn.ReLU(inplace=True),
            nn.MaxPool2d(2),
            nn.Conv2d(base * 2, base * 4, 3, padding=1), nn.BatchNorm2d(base * 4), nn.ReLU(inplace=True),
        )
        self.pool = nn.AdaptiveAvgPool2d(1)
        self.head = nn.Linear(base * 4, num_classes)

    def forward(self, x):
        x = self.pool(self.features(x)).flatten(1)
        return self.head(x)


def build_model():
    return SmallClassifier()
