"""Training entry point (classification; generated by model-scaffold).
Reproducible: every RNG seeded, cuDNN deterministic, train loader from the TRAIN split."""
import random
import numpy as np
import torch
from torch.utils.data import DataLoader

from dataset import ScaffoldDataset
from losses import build_loss
from model import build_model

SEED = 42
REPO_ROOT = "."
MANIFEST = "_seed_manifest.csv"


def seed_everything(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


def _device():
    if torch.cuda.is_available():
        return torch.device("cuda")
    if torch.backends.mps.is_available():   # Apple Silicon GPU (M-series)
        return torch.device("mps")
    return torch.device("cpu")


def main():
    seed_everything(SEED)
    device = _device()
    print("device:", device)
    train_ds = ScaffoldDataset(MANIFEST, REPO_ROOT, split="train")
    val_ds = ScaffoldDataset(MANIFEST, REPO_ROOT, split="val")
    train_loader = DataLoader(train_ds, batch_size=128, shuffle=True, num_workers=0)
    val_loader = DataLoader(val_ds, batch_size=256, shuffle=False, num_workers=0)
    model = build_model().to(device)
    criterion = build_loss()
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
    best_val = float("inf")
    for epoch in range(20):
        model.train()
        for x, y in train_loader:
            x, y = x.to(device), y.to(device)
            optimizer.zero_grad()
            loss = criterion(model(x), y)
            loss.backward()
            optimizer.step()
        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for x, y in val_loader:
                x, y = x.to(device), y.to(device)
                val_loss += criterion(model(x), y).item()
        val_loss /= max(len(val_loader), 1)
        marker = ""
        if val_loss < best_val:
            best_val = val_loss
            torch.save({"epoch": epoch, "model": model.state_dict(), "seed": SEED}, "best.pt")
            marker = "  <- best"
        print(f"epoch {epoch:2d}  val_loss {val_loss:.4f}{marker}")


if __name__ == "__main__":
    main()
