#!/usr/bin/env bash
# render_pandoc.sh — Pandoc citeproc wrapper for manuscript rendering with journal CSL.
# (Renamed from render_manuscript.sh on 2026-05-01 when relocated to /manage-refs.)
#
# Usage:
#   render_pandoc.sh -j <journal> -i <input.md> -b <refs.bib> [-o <out.docx>] [-t <reference.docx>] [-- <extra pandoc args>]
#
# Example:
#   render_pandoc.sh -j european-radiology -i manuscript.md -b references.bib -o manuscript_v4.docx
#
# Citation syntax in markdown body: [@bibkey] or [@key1; @key2]
# References section is auto-generated by pandoc citeproc — do NOT hand-write a References list.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CSL_DIR="${SCRIPT_DIR}/../citation_styles"

usage() {
  cat >&2 <<EOF
Usage: $(basename "$0") -j <journal> -i <input.md> -b <refs.bib> [-o <out>] [-t <reference.docx>] [-f <format>]

Options:
  -j  Journal CSL name (without .csl). Examples: european-radiology, radiology,
      american-journal-of-roentgenology, cardiovascular-and-interventional-radiology,
      korean-journal-of-radiology, vancouver. See \${CSL_DIR}/README.md.
  -i  Input markdown manuscript
  -b  BibTeX bibliography file
  -o  Output path (default: <input>.docx). Format inferred from extension.
  -t  Optional Word reference .docx for styles/fonts
  -f  Force output format (docx|pdf|html). Default: from -o extension or docx.
  -S  Skip the pre-render reference audit (verify-refs) gate (NOT recommended).
  -h  Help

Pass-through: any args after '--' go directly to pandoc.

Exit codes: 0 ok; 1 usage; 2 missing CSL/input/bib; 3 reference audit found
FABRICATED/MISMATCH; 5 citation(s) not found in the .bib (rendered as '(key?)');
other non-zero codes come from pandoc itself.

The pre-render gate delegates to /verify-refs (when found alongside, or via
\$MEDSCI_VERIFY_REFS) and blocks the render on fabricated/mismatched citations.
EOF
  exit 1
}

JOURNAL=""
INPUT=""
BIB=""
OUTPUT=""
REFDOC=""
FORMAT=""
SKIP_AUDIT=0

while getopts ":j:i:b:o:t:f:hS" opt; do
  case "$opt" in
    j) JOURNAL="$OPTARG" ;;
    i) INPUT="$OPTARG" ;;
    b) BIB="$OPTARG" ;;
    o) OUTPUT="$OPTARG" ;;
    t) REFDOC="$OPTARG" ;;
    f) FORMAT="$OPTARG" ;;
    S) SKIP_AUDIT=1 ;;
    h|*) usage ;;
  esac
done
shift $((OPTIND - 1))

[[ -z "$JOURNAL" || -z "$INPUT" || -z "$BIB" ]] && usage

CSL_FILE="${CSL_DIR}/${JOURNAL}.csl"
if [[ ! -f "$CSL_FILE" ]]; then
  echo "ERROR: CSL not found: $CSL_FILE" >&2
  echo "Available styles:" >&2
  ls -1 "${CSL_DIR}" | grep '\.csl$' | sed 's/\.csl$//' | sed 's/^/  /' >&2
  exit 2
fi
[[ -f "$INPUT" ]] || { echo "ERROR: input not found: $INPUT" >&2; exit 2; }
[[ -f "$BIB" ]]   || { echo "ERROR: bib not found: $BIB" >&2; exit 2; }

# Pre-render reference audit gate — delegates to /verify-refs and blocks the render on
# fabricated / mismatched citations (e.g., #2..#N family-name hallucinations or author-count
# mismatches) before they reach the PDF/DOCX. Best-effort: if verify-refs is not installed
# alongside (and $MEDSCI_VERIFY_REFS is unset) the gate is skipped with a warning, so a
# standalone manage-refs copy still renders. Opt out explicitly with -S.
# UNVERIFIED rows (a lookup that confirmed nothing, including every row when the network is
# down) exit 0 and do not block, but they are not "clean": the render says how many there are.
if [[ "$SKIP_AUDIT" -eq 0 ]]; then
  VR="${MEDSCI_VERIFY_REFS:-${SCRIPT_DIR}/../../verify-refs/scripts/verify_refs.py}"
  if [[ -f "$VR" ]] && command -v python3 >/dev/null 2>&1; then
    echo "[render] pre-render reference audit (verify-refs) on $BIB ..." >&2
    set +e
    audit_out="$(python3 "$VR" "$BIB")"
    audit_rc=$?
    set -e
    [[ -n "$audit_out" ]] && printf '%s\n' "$audit_out" >&2
    n_unverified="$(printf '%s\n' "$audit_out" | sed -n 's/^ *"UNVERIFIED": *\([0-9][0-9]*\).*/\1/p' | head -n 1)"
    if [[ "$audit_rc" -eq 0 && -n "$n_unverified" && "$n_unverified" != "0" ]]; then
      echo "[render] reference audit: NOT clean — $n_unverified reference(s) UNVERIFIED (nothing confirmed them; no FABRICATED / MISMATCH found). Continuing render; confirm each by hand before submission (see qc/reference_audit.json)." >&2
    elif [[ "$audit_rc" -eq 0 ]]; then
      echo "[render] reference audit: clean" >&2
    elif [[ "$audit_rc" -eq 1 ]]; then
      echo "ERROR: reference audit found FABRICATED / MISMATCH / duplicate citations (see qc/reference_audit.json)." >&2
      echo "       Fix the .bib (or the Zotero record, since BBT overwrites manual .bib edits), or pass -S to skip (NOT recommended)." >&2
      exit 3
    else
      echo "[render] WARNING: reference audit did not complete (exit $audit_rc — e.g., no network, bad input, or no references); continuing render." >&2
    fi
  else
    echo "[render] (verify-refs not found alongside; skipping pre-render audit — set \$MEDSCI_VERIFY_REFS or pass -S)" >&2
  fi
fi

if [[ -z "$OUTPUT" ]]; then
  OUTPUT="${INPUT%.*}.docx"
fi
if [[ -z "$FORMAT" ]]; then
  case "${OUTPUT##*.}" in
    docx) FORMAT="docx" ;;
    pdf)  FORMAT="pdf" ;;
    html) FORMAT="html" ;;
    *)    FORMAT="docx" ;;
  esac
fi

# Run after citeproc: source locations are needed to resolve citations, but must
# not survive as custom document properties in an artifact shared with others.
ARGS=(--citeproc --csl="$CSL_FILE" --bibliography="$BIB"
      --lua-filter="${SCRIPT_DIR}/strip_source_metadata.lua" -t "$FORMAT" -o "$OUTPUT")
[[ -n "$REFDOC" && -f "$REFDOC" ]] && ARGS+=(--reference-doc="$REFDOC")

# Unresolved citations: citeproc does not fail on a key it cannot find. It prints `(key?)` into the
# manuscript, warns on stderr and exits 0 — so the render used to report "ok" on a document with a
# broken citation in it. Read pandoc's structured log (--log, JSON) for that warning and fail.
PANDOC_LOG="$(mktemp)"
# The script's only EXIT trap. A later `trap ... EXIT` replaces it: fold any new cleanup into this one.
trap 'rm -f "$PANDOC_LOG"' EXIT
ARGS+=(--log="$PANDOC_LOG")

echo "[render] journal=$JOURNAL csl=$(basename "$CSL_FILE") in=$INPUT bib=$BIB out=$OUTPUT" >&2
pandoc "${ARGS[@]}" "$@" "$INPUT"
missing_cites="$(grep -oE '"message": *"citation [^"]+ not found"' "$PANDOC_LOG" \
  | sed -E 's/^"message": *"citation (.+) not found"$/\1/' || true)"
if [[ -n "$missing_cites" ]]; then
  echo "ERROR: unresolved citation(s) — cited in $INPUT but not found in $BIB; pandoc printed them as '(key?)' in $OUTPUT:" >&2
  printf '%s\n' "$missing_cites" | sed 's/^/  [@/; s/$/]/' >&2
  echo "       Add the entries to the .bib (or fix the keys), then render again. Do not submit $OUTPUT." >&2
  exit 5
fi
echo "[render] ok → $OUTPUT" >&2
