#!/usr/bin/env python3
"""Every image we ship must be one we are allowed to ship.

This repository is **MIT-licensed** and it is distributed — on npm, and as a classroom ZIP that every
user downloads. MIT tells the world it may "use, copy, modify, merge, publish, distribute,
sublicense, and sell" what is inside. That is a promise about *our* rights, and we can only make it
about material we actually hold.

On 2026-07-14 we found ten PNGs under `skills/make-figures/references/exemplar_diagrams/` that had
been **cropped from published papers**. The directory's own README said so, and promised each came
with a sidecar recording "source PDF, page, DOI, crop coords" — and that the sidecar "records DOI and
source for every exemplar."

It recorded `label`, `figure_type`, `dpi`. No source, no DOI, no licence. Eight of the eighteen
images had no sidecar at all. The safeguard the README described had never been written, and nothing
checked. The README also argued fair use on the grounds that exemplars are "not redistributed as part
of generated figures" — true, and beside the point: they were redistributed as part of the *package*.

**A figure you may legally read is not a figure you may legally ship.**

So: every raster image under `skills/` (the payload) must either be

  * **ours** — generated by a script in this repository, listed in SELF_GENERATED below; or
  * **licensed for redistribution** — accompanied by a `<name>.meta.yaml` declaring `source` and a
    `license` that permits it (CC-BY, CC0, public domain, or an explicit own-work marker).

An image with neither fails the build. There is no "probably fine" tier, because the whole failure
was a "probably fine" that nobody had checked.

Usage:
    check_bundled_media_license.py [--strict]

Stdlib only.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILLS = ROOT / "skills"

RASTER = {".png", ".jpg", ".jpeg", ".gif", ".webp", ".tif", ".tiff", ".bmp"}

# Images this project renders itself. Each entry is a filename glob plus the script that makes it —
# named, so that "it is ours" is a claim someone wrote down rather than an assumption.
SELF_GENERATED = {
    "template_output*.png": "skills/make-figures/scripts/generate_flow_diagram.R",
}

# Licences that permit redistribution inside an MIT-licensed package.
OK_LICENSES = re.compile(
    r"\b(cc0|cc-?by(-sa)?(-\d\.\d)?|public[- ]domain|own[- ]work|mit|apache|bsd)\b",
    re.IGNORECASE,
)


def self_generated(p: Path) -> bool:
    return any(p.match(g) for g in SELF_GENERATED)


def sidecar_ok(p: Path) -> tuple[bool, str]:
    meta = p.with_suffix("").with_suffix(".meta.yaml")
    if not meta.exists():
        meta = p.parent / (p.stem + ".meta.yaml")
    if not meta.exists():
        return False, "no <name>.meta.yaml beside it"

    text = meta.read_text(encoding="utf-8", errors="ignore")
    has_source = re.search(r"^\s*(source|doi|url)\s*:\s*\S", text, re.MULTILINE)
    lic = re.search(r"^\s*licen[sc]e\s*:\s*(.+)$", text, re.MULTILINE)

    if not has_source:
        return False, "meta.yaml declares no source / doi / url"
    if not lic:
        return False, "meta.yaml declares no license"
    if not OK_LICENSES.search(lic.group(1)):
        return False, f"license {lic.group(1).strip()!r} does not clearly permit redistribution"
    return True, ""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--strict", action="store_true", help="exit 1 on any image we cannot ship")
    a = ap.parse_args()

    images = sorted(p for p in SKILLS.rglob("*") if p.suffix.lower() in RASTER and p.is_file())
    bad: list[tuple[Path, str]] = []
    ours = 0
    licensed = 0

    for p in images:
        if self_generated(p):
            ours += 1
            continue
        ok, why = sidecar_ok(p)
        if ok:
            licensed += 1
        else:
            bad.append((p, why))

    if not bad:
        print(f"OK: all {len(images)} bundled image(s) may be shipped "
              f"({ours} generated by this project, {licensed} licensed for redistribution).")
        return 0

    print(f"BUNDLED_MEDIA_UNLICENSED: {len(bad)} of {len(images)} image(s) cannot be shipped.\n")
    for p, why in bad:
        print(f"  {p.relative_to(ROOT)}")
        print(f"      {why}")
    print(
        "\nThis repository is MIT-licensed and is downloaded by every user. Shipping an image means\n"
        "granting the world the right to copy, modify and sell it — which we can only do for material\n"
        "we hold. Either:\n"
        "  * it is ours -> add its filename pattern to SELF_GENERATED in this script, naming the\n"
        "    script that renders it; or\n"
        "  * it is someone else's -> add a <name>.meta.yaml with `source`/`doi` AND a `license` that\n"
        "    permits redistribution (CC-BY, CC0, public domain); or\n"
        "  * we cannot demonstrate permission -> do not ship it. Keep it locally; a file you never\n"
        "    commit is never redistributed.\n"
        "\nA figure you may legally read is not a figure you may legally ship."
    )
    return 1 if a.strict else 0


if __name__ == "__main__":
    sys.exit(main())
