#!/usr/bin/env python3
"""Reproducible medical-imaging training-repo scaffold generator (model-scaffold).

Emits a runnable PyTorch training repo for a medical-imaging segmentation task with
the reproducibility guarantees baked in *by construction*, so the produced code
passes the lane's integrity gates without hand-editing:

  - a PATIENT-LEVEL, SEED-LOCKED split written as an auditable artifact
    (`splits/split_assignment.csv` + `splits/split_seed.txt`) — every image of a
    patient lands in exactly one of train/val/test, so the split is disjoint by
    construction and `check_split_leakage.py` (/model-validation) passes;
  - a `train.py` that seeds random / numpy / torch (+ cuda) and sets cuDNN
    deterministic, builds the training DataLoader from the TRAIN split only, and an
    `evaluate.py` that runs inference under `model.eval()` + `torch.no_grad()` — so
    `check_training_hygiene.py` passes;
  - `model.py` (a small configurable U-Net), `dataset.py` (reads the split table,
    never re-splits), `losses.py`, `config.yaml` (the single source of truth),
    `requirements.txt`, `REPRODUCIBILITY.md`, and a `methods_stub.md` with
    `[VERIFY: ...]` placeholders (no fabricated numbers).

It INTEGRATES with the ecosystem (PyTorch; MONAI / nnU-Net / TorchIO referenced in
the generated requirements + guide) — it does not reimplement them. The generated
repo is what the user runs on Colab / a lab GPU; this generator and the lane's gates
only verify the NETWORK-FREE parts (split disjointness, training hygiene, forward
shape). Heavy training is the user's to run.

INPUTS
  --manifest   CSV listing one row per image with a patient/subject ID column
               (and optional image / label path columns, copied into dataset.py's
               expected schema). Required.
  --id-col     patient/subject ID column in the manifest (default: auto-detect
               patient_id / subject_id / case_id / id).
  --task       segmentation (default; the only task in this phase).
  --arch       unet (default) — a small configurable 2-D U-Net.
  --out        output repo directory (default: model_repo).
  --seed       split + training seed (default 42).
  --val-frac / --test-frac   patient-level split fractions (default 0.15 / 0.15).
  --in-channels / --out-channels   model channels (default 1 / 1).
  --base-channels   U-Net base width (default 16).

OUTPUT
  A self-contained repo under --out (tree printed to stdout). Deterministic given the
  manifest + seed.

Stdlib + numpy only (numpy is used solely for the deterministic patient-level split;
the GENERATED code uses torch, which the user installs). Exit codes: 0 ok,
2 input/usage error.
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

import numpy as np

ID_HINTS = ("patient_id", "subject_id", "case_id", "patientid", "subjectid", "id", "pid", "mrn")

# --------------------------------------------------------------------------- #
# Generated-file templates. Placeholders are __TOKENS__ replaced by render().   #
# The emitted Python is valid and hygienic BY CONSTRUCTION (seeds all RNGs,      #
# cuDNN-deterministic, train-only loader, eval()/no_grad() inference).           #
# --------------------------------------------------------------------------- #

MODEL_PY = r'''"""Small configurable 2-D U-Net (generated by model-scaffold).

A plain encoder-decoder with skip connections (Ronneberger 2015). Kept intentionally
small and CPU-runnable so a forward pass can be smoke-tested without a GPU. Swap in
MONAI's UNet / SegResNet or an nnU-Net plan for production (see REPRODUCIBILITY.md).
"""
import torch
import torch.nn as nn


def _cbr(cin, cout):
    return nn.Sequential(
        nn.Conv2d(cin, cout, 3, padding=1), nn.BatchNorm2d(cout), nn.ReLU(inplace=True),
        nn.Conv2d(cout, cout, 3, padding=1), nn.BatchNorm2d(cout), nn.ReLU(inplace=True),
    )


class UNet(nn.Module):
    def __init__(self, in_channels=__IN_CH__, out_channels=__OUT_CH__, base=__BASE__):
        super().__init__()
        self.enc1 = _cbr(in_channels, base)
        self.enc2 = _cbr(base, base * 2)
        self.enc3 = _cbr(base * 2, base * 4)
        self.pool = nn.MaxPool2d(2)
        self.bottleneck = _cbr(base * 4, base * 8)
        self.up3 = nn.ConvTranspose2d(base * 8, base * 4, 2, stride=2)
        self.dec3 = _cbr(base * 8, base * 4)
        self.up2 = nn.ConvTranspose2d(base * 4, base * 2, 2, stride=2)
        self.dec2 = _cbr(base * 4, base * 2)
        self.up1 = nn.ConvTranspose2d(base * 2, base, 2, stride=2)
        self.dec1 = _cbr(base * 2, base)
        self.head = nn.Conv2d(base, out_channels, 1)

    def forward(self, x):
        e1 = self.enc1(x)
        e2 = self.enc2(self.pool(e1))
        e3 = self.enc3(self.pool(e2))
        b = self.bottleneck(self.pool(e3))
        d3 = self.dec3(torch.cat([self.up3(b), e3], dim=1))
        d2 = self.dec2(torch.cat([self.up2(d3), e2], dim=1))
        d1 = self.dec1(torch.cat([self.up1(d2), e1], dim=1))
        return self.head(d1)


def build_model():
    return UNet()
'''

DATASET_PY = r'''"""Dataset that reads the FROZEN split assignment (generated by model-scaffold).

The split was decided once, at scaffold time, and recorded in
splits/split_assignment.csv. This dataset only READS it (filtering by split) and
never re-splits, so the partition stays patient-disjoint and reproducible. Replace
the _load_image / _load_label stubs with your DICOM / NIfTI / TIFF reader
(nibabel / pydicom / tifffile / TorchIO / MONAI transforms).
"""
import csv
from pathlib import Path

import torch
from torch.utils.data import Dataset

ID_COL = "__ID_COL__"


def _read_split(repo_root):
    root = Path(repo_root)
    assign = {}
    with (root / "splits" / "split_assignment.csv").open(encoding="utf-8") as f:
        for row in csv.DictReader(f):
            assign[row[ID_COL]] = row["split"]
    return assign


class ScaffoldDataset(Dataset):
    """One item per manifest row whose patient is in `split`."""

    def __init__(self, manifest_csv, repo_root, split, transform=None):
        assign = _read_split(repo_root)
        self.rows = []
        with open(manifest_csv, encoding="utf-8") as f:
            for row in csv.DictReader(f):
                if assign.get(row[ID_COL]) == split:
                    self.rows.append(row)
        self.transform = transform

    def __len__(self):
        return len(self.rows)

    def _load_image(self, row):
        raise NotImplementedError("plug in your DICOM/NIfTI/TIFF reader -> CxHxW float tensor")

    def _load_label(self, row):
        raise NotImplementedError("plug in your mask reader -> 1xHxW float tensor in {0,1}")

    def __getitem__(self, i):
        row = self.rows[i]
        x, y = self._load_image(row), self._load_label(row)
        if self.transform is not None:
            x, y = self.transform(x, y)
        return x, y
'''

LOSSES_PY = r'''"""Segmentation losses (generated by model-scaffold)."""
import torch
import torch.nn as nn


class DiceBCELoss(nn.Module):
    """BCEWithLogits + soft Dice — a robust default for imbalanced masks."""

    def __init__(self, smooth=1.0):
        super().__init__()
        self.bce = nn.BCEWithLogitsLoss()
        self.smooth = smooth

    def forward(self, logits, target):
        bce = self.bce(logits, target)
        probs = torch.sigmoid(logits)
        num = 2 * (probs * target).sum(dim=(1, 2, 3)) + self.smooth
        den = probs.sum(dim=(1, 2, 3)) + target.sum(dim=(1, 2, 3)) + self.smooth
        dice = 1 - (num / den).mean()
        return bce + dice
'''

TRAIN_PY = r'''"""Training entry point (generated by model-scaffold).

Reproducibility is baked in: every RNG is seeded and cuDNN is deterministic, the
training DataLoader is built from the TRAIN split only, and the best model is
selected on the VAL split (never the test set). Fill in the dataset I/O stubs, then
run on your GPU / Colab. No metric is hard-coded here.
"""
import random

import numpy as np
import torch
from torch.utils.data import DataLoader

from dataset import ScaffoldDataset
from losses import DiceBCELoss
from model import build_model

SEED = __SEED__
REPO_ROOT = "."
MANIFEST = "__MANIFEST_NAME__"


def seed_everything(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


def main():
    seed_everything(SEED)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    train_ds = ScaffoldDataset(MANIFEST, REPO_ROOT, split="train")
    val_ds = ScaffoldDataset(MANIFEST, REPO_ROOT, split="val")
    train_loader = DataLoader(train_ds, batch_size=4, shuffle=True, num_workers=4)
    val_loader = DataLoader(val_ds, batch_size=4, shuffle=False, num_workers=4)

    model = build_model().to(device)
    criterion = DiceBCELoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

    best_val = float("inf")
    for epoch in range(50):
        model.train()
        for x, y in train_loader:
            x, y = x.to(device), y.to(device)
            optimizer.zero_grad()
            loss = criterion(model(x), y)
            loss.backward()
            optimizer.step()

        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for x, y in val_loader:
                x, y = x.to(device), y.to(device)
                val_loss += criterion(model(x), y).item()
        val_loss /= max(len(val_loader), 1)
        if val_loss < best_val:
            best_val = val_loss
            torch.save({"epoch": epoch, "model": model.state_dict(),
                        "optimizer": optimizer.state_dict(), "seed": SEED},
                       "best.pt")


if __name__ == "__main__":
    main()
'''

EVALUATE_PY = r'''"""Held-out evaluation (generated by model-scaffold).

Loads the best checkpoint, runs inference on the TEST split under model.eval() +
torch.no_grad(), and writes a per-case predictions table. Compute task-correct
metrics (Dice + HD95/NSD, with CIs) downstream via /model-evaluation and
/analyze-stats — this script only produces predictions, never fabricated scores.
"""
import csv

import torch
from torch.utils.data import DataLoader

from dataset import ScaffoldDataset
from model import build_model

REPO_ROOT = "."
MANIFEST = "__MANIFEST_NAME__"


def main():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    test_ds = ScaffoldDataset(MANIFEST, REPO_ROOT, split="test")
    test_loader = DataLoader(test_ds, batch_size=1, shuffle=False)

    model = build_model().to(device)
    ckpt = torch.load("best.pt", map_location=device)
    model.load_state_dict(ckpt["model"])
    model.eval()

    rows = []
    with torch.no_grad():
        for i, (x, y) in enumerate(test_loader):
            x = x.to(device)
            logits = model(x)
            probs = torch.sigmoid(logits)
            rows.append({"index": i, "pred_positive_voxels": int((probs > 0.5).sum().item())})

    with open("predictions.csv", "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=["index", "pred_positive_voxels"])
        w.writeheader()
        w.writerows(rows)


if __name__ == "__main__":
    main()
'''

CONFIG_YAML = """# Single source of truth for this scaffolded run (generated by model-scaffold).
task: __TASK__
arch: __ARCH__
seed: __SEED__
id_col: __ID_COL__
in_channels: __IN_CH__
out_channels: __OUT_CH__
base_channels: __BASE__
split:
  val_frac: __VAL_FRAC__
  test_frac: __TEST_FRAC__
  assignment: splits/split_assignment.csv
  seed_file: splits/split_seed.txt
manifest: __MANIFEST_NAME__
"""

REQUIREMENTS = """# Generated by model-scaffold. Pin exact versions before publishing.
torch
numpy
# Recommended medical-imaging stack (integrate, do not reimplement):
# monai          # UNet/SegResNet, transforms, metrics (Dice/HD95/NSD)
# torchio        # 3-D spatial/intensity augmentation
# nibabel        # NIfTI I/O
# pydicom        # DICOM I/O
# tifffile       # TIFF I/O
# tensorboard    # training curves
"""

REPRO_MD = """# Reproducibility

This repo was generated by `model-scaffold` with the reproducibility guarantees baked
in. Record the exact environment before publishing.

- **Split**: patient-level, seed-locked. The assignment is frozen in
  `splits/split_assignment.csv` (seed in `splits/split_seed.txt`, = `__SEED__`).
  Every image of a patient is in exactly one of train/val/test (disjoint by
  construction). Verify with `/model-validation`:
  `python3 check_split_leakage.py --splits splits/split_assignment.csv --strict`.
- **Seed**: `__SEED__`, applied to `random`, `numpy`, `torch`, `torch.cuda`; cuDNN set
  deterministic (`train.py: seed_everything`). Note GPU non-determinism caveats for
  some ops; report metrics as mean ± SD over >= 3 seeds.
- **Model**: `model.py` (configurable U-Net, in=`__IN_CH__` out=`__OUT_CH__`
  base=`__BASE__`). For production, swap in MONAI `UNet`/`SegResNet` or an nnU-Net plan.
- **Environment** (fill in): `python --version`, `pip freeze` (torch/monai/... pins),
  CUDA / driver, GPU model, git commit of this repo.
- **Data**: plug your reader into `dataset.py` (`_load_image` / `_load_label`).

## How to reproduce
1. `pip install -r requirements.txt` (pinned).
2. Implement `dataset.py` I/O for your modality.
3. `python train.py`  (selects best model on the VAL split; writes `best.pt`).
4. `python evaluate.py`  (writes `predictions.csv` on the TEST split).
5. Metrics + CIs via `/model-evaluation` -> `/analyze-stats`; reporting via
   `/check-reporting` (CLAIM 2024 / TRIPOD+AI).
"""

METHODS_MD = """# Methods stub (generated by model-scaffold — fill the [VERIFY] placeholders)

A 2-D U-Net (`__ARCH__`; in=`__IN_CH__`, out=`__OUT_CH__`, base width `__BASE__`) was
trained for __TASK__. Data were split at the **patient level** (train / validation /
test = [VERIFY: report n patients per split from splits/split_assignment.csv];
fractions val=__VAL_FRAC__, test=__TEST_FRAC__), with the assignment frozen and
seed-locked (seed __SEED__) so that no patient contributed images to more than one
partition. The model was optimised with Adam (learning rate 1e-3) and a combined
soft-Dice + binary-cross-entropy loss; the best model was selected on the validation
split. All random number generators (Python, NumPy, PyTorch, CUDA) were seeded and
cuDNN was set to deterministic mode. Held-out performance is reported as
[VERIFY: Dice and a boundary metric (HD95 / NSD), per structure, with 95% CIs over
>= 3 seeds] on the test split, which was used once.
"""


def _pick_id_col(header, explicit):
    if explicit:
        if explicit in header:
            return explicit
        sys.stderr.write(f"ERROR: --id-col '{explicit}' not in manifest header {header}\n")
        sys.exit(2)
    norm = {h.strip().lower().replace("_", "").replace(" ", ""): h for h in header}
    for hint in ID_HINTS:
        key = hint.replace("_", "")
        if key in norm:
            return norm[key]
    sys.stderr.write(f"ERROR: no ID column found in {header}; pass --id-col\n")
    sys.exit(2)


def split_patients(ids, seed, val_frac, test_frac):
    """Deterministic patient-level split. Returns {patient_id: 'train'|'val'|'test'}."""
    uniq = sorted(set(ids))
    rng = np.random.default_rng(seed)
    order = [uniq[i] for i in rng.permutation(len(uniq))]
    n = len(order)
    n_test = round(n * test_frac)
    n_val = round(n * val_frac)
    assign = {}
    for pid in order[:n_test]:
        assign[pid] = "test"
    for pid in order[n_test:n_test + n_val]:
        assign[pid] = "val"
    for pid in order[n_test + n_val:]:
        assign[pid] = "train"
    return assign


def render(tmpl, repl):
    out = tmpl
    for k, v in repl.items():
        out = out.replace(k, str(v))
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description="Reproducible medical-imaging training-repo scaffold.")
    ap.add_argument("--manifest", required=True, help="CSV: one row per image, with a patient ID column")
    ap.add_argument("--id-col", help="patient/subject ID column (auto-detected if omitted)")
    ap.add_argument("--task", default="segmentation", choices=["segmentation"])
    ap.add_argument("--arch", default="unet", choices=["unet"])
    ap.add_argument("--out", default="model_repo", help="output repo directory")
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--val-frac", type=float, default=0.15)
    ap.add_argument("--test-frac", type=float, default=0.15)
    ap.add_argument("--in-channels", type=int, default=1)
    ap.add_argument("--out-channels", type=int, default=1)
    ap.add_argument("--base-channels", type=int, default=16)
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    man = Path(args.manifest)
    if not man.is_file():
        sys.stderr.write(f"ERROR: --manifest not found: {args.manifest}\n")
        return 2
    with man.open(encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        header = reader.fieldnames or []
        rows = list(reader)
    if not rows:
        sys.stderr.write("ERROR: manifest has no rows\n")
        return 2
    id_col = _pick_id_col(header, args.id_col)
    ids = [r[id_col] for r in rows if (r.get(id_col) or "").strip()]
    if not ids:
        sys.stderr.write(f"ERROR: no values in ID column '{id_col}'\n")
        return 2

    assign = split_patients(ids, args.seed, args.val_frac, args.test_frac)

    out = Path(args.out)
    (out / "splits").mkdir(parents=True, exist_ok=True)

    # Auditable, frozen split artifact (sorted for determinism).
    with (out / "splits" / "split_assignment.csv").open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow([id_col, "split"])
        for pid in sorted(assign):
            w.writerow([pid, assign[pid]])
    (out / "splits" / "split_seed.txt").write_text(f"{args.seed}\n", encoding="utf-8")

    repl = {
        "__SEED__": args.seed, "__IN_CH__": args.in_channels, "__OUT_CH__": args.out_channels,
        "__BASE__": args.base_channels, "__TASK__": args.task, "__ARCH__": args.arch,
        "__ID_COL__": id_col, "__VAL_FRAC__": args.val_frac, "__TEST_FRAC__": args.test_frac,
        "__MANIFEST_NAME__": man.name,
    }
    files = {
        "model.py": MODEL_PY, "dataset.py": DATASET_PY, "losses.py": LOSSES_PY,
        "train.py": TRAIN_PY, "evaluate.py": EVALUATE_PY, "config.yaml": CONFIG_YAML,
        "requirements.txt": REQUIREMENTS, "REPRODUCIBILITY.md": REPRO_MD,
        "methods_stub.md": METHODS_MD,
    }
    for name, tmpl in files.items():
        (out / name).write_text(render(tmpl, repl), encoding="utf-8")

    n_train = sum(1 for v in assign.values() if v == "train")
    n_val = sum(1 for v in assign.values() if v == "val")
    n_test = sum(1 for v in assign.values() if v == "test")
    if not args.quiet:
        print(f"scaffolded {args.task}/{args.arch} repo -> {out}/")
        print(f"  patients: {len(assign)} (train={n_train} val={n_val} test={n_test}), seed={args.seed}")
        print("  files: " + ", ".join(sorted(files) + ["splits/split_assignment.csv", "splits/split_seed.txt"]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
